### ISSUE TITLE
Race conditions related to uploaded file names and hike page names

### ISSUE THREAD

**Issue by tjsandberg** [krcowles/ktesa#12]
When a gpx file is uploaded to the site, there is a window of time between checking for a duplicate file name and creating the new file. During that window, another file of the same name could be created. See the code snip below from build/buildFunctions.php.

I also think there are similar issues elsewhere in the code:
 - photo uploads
 - new hike page creation 

Code snip from build/buildFunctions.php
        if (file_exists($saveloc)) {
            $dupdata = dupFileName($filename);
            $filename = $dupdata[0];
            $saveloc = $fileloc . $filename;
            $msg .=  $dupdata[1] . "<br />";
        }
        if (!move_uploaded_file($tmp_upload, $saveloc)) {
            $nomove = "Could not save {$filename} to site: contact Site Master";
            throw new Exception($nomove);
        } else {
            $msg .= "'{$filename}' Successfully uploaded to site";
        }

**Comment by krcowles** [comment]
Interesting discovery. Do you have any recommendations on this?

**Comment by tjsandberg** [comment]
Maybe use flock() on the gpx directory. Then check whether the file exists and create it before unlocking the directory.
