### ISSUE TITLE
Highlighting tracks does not occur if zoom level doesn't change

### ISSUE THREAD

**Issue by krcowles** [krcowles/ktesa#13]
When using the 'zoom to' icon in the side table and selecting a hike (e.g. Birdhouse Ridge), the track zooms and centers to the hike and the track is highlighted. If a second hike's 'zoom to' icon is clicked (e.g. Hawk Watch Trail), the zoom occurs, but the track is not highlighted.

**Comment by tjsandberg** [comment]
I tested the new branch on my machine and it seems to fix the problem. I'd say this one is ready to merge to master. It should be a FF. If you want, maybe first upload the branch to a test site. Either way is fine with me.

**Comment by krcowles** [comment]
Thanks. I did create a test site at [https://nmhikes.com/master_b2031a5b](url)  and merged to master and pushed.

**Comment by tjsandberg** [comment]
I don't see that you pushed master.
