### ISSUE TITLE
Remove serialized data in HIKES table (aoimg*)

### ISSUE THREAD

**Issue by krcowles** [krcowles/ktesa#16]
This is step 1 of a 2-part process. In this step, any data extant in the HIKES columns *aoimg1* or *aoimg2* is removed. This primarily affects 1 hike: **Albuquerque Volcanoes**, which had a map of the volcano area in the photos section. The removal of these fields simplifies the hike row data and formation scripts. After uploading the proposed changes to a test site (and subsequently to main), it is proposed to upload the volcano map by editing that hike page. At this point, the page will be renewed, but the image will now exist in the pictures/ directory instead of as serialized data in HIKES. Two obsolete elevation profiles are also eliminated in the **Tesuque - Upper** hike page (placed there before the elevation chart was enabled on the hike page). A third image, Montosa.jpg will be used to create a new "Cluster" page for the hikes on Chino mesa (TBD), and is removed from the **Twin Hills** hike page. The second step of this 2-part process will be to remove unused fields in the HIKES table (which will include aoimg1 and aoimg2).

**Comment by krcowles** [comment]
The index page images (.jpg maps) have resided in the images directory. I didn't see the need to move them to the pictures directory as they aren't hike page photos/images. I merely placed placed their references in the TSV table to elminate the aoimg serialized data, and changed the index page template to create the proper src link. For actual hike page images (e.g. volcanoes map), those seemed to belong in the pictures directory as they appear with other photos on the hike page and belong to the reference hike index no. I didn't want to *manually* move the volcanoes map because our code creates the unique thumb value, and it would be easy to mess that up with a manual calculation and then manual entry in the db. For that one, it seemed best to edit the ABQ Volcanoes page and upload the map once the branch is tested and moved to main. The only obsolete file is the Ski2ForestRd.jpg. I agree that one should be removed from the directory in this branch (removeAoimgs). Maybe that's done in an integration branch, as no code is affected. I await feedback before doing anything.

**Comment by tjsandberg** [comment]
Process points:

1. I guess your latest comment is in response to what I had written in your pull request #17. If so, I think we should try to keep the discussion in one place. For reference, here's what I had written:
> I don't think we want to merge this branch to master yet, as we need to delete the now-obsolete image files and move at least one image file to the pictures directory as you explained in Issue #16. So we either need a new integration branch, or more changes need to be merged into this branch. Maybe use Issue #16 to detail the plan for this.
2. I think we agreed on the last Hangouts that for now we will create an Issue as the starting point for all code changes. So I think it's good to have the discussion here on the issue thread.
3. I think we should link the pull request to this issue, so I will do that right after posting this comment.

I'll try to write more on the substance later.

**Comment by krcowles** [comment]
1. I thought you were essentially telling me to use the existing issue 16 for outlining the plan, which included the reasoning behind the plan, so I put the response there.
2. We did agree on using issues, for starting point. Obviously, I forgot to link it to the issue. Still learning the process... 
3. Looks like you already did that - good.

**Comment by krcowles** [comment]
With the implementation of cluster pages (replacement of index pages), the serialized data fields were no longer required and have been deleted, rendering this issue closed.
