### ISSUE TITLE
Logging in while on reload database page reloads the database again

### ISSUE THREAD

**Issue by tjsandberg** [krcowles/ktesa#26]
Here's how to reproduce the problem. It's an odd sequence but worth noting at least.
1. Log out of the site.
2. Go to the admin page by typing in the address: nmhikes.com/admin/admintools.php.
3. Reload the database.
4. After the database reload completes, log into the site. The page refreshes and reloads the database again.

**Comment by krcowles** [comment]
The new login methodology has eliminated this problem; at least I can no longer reproduce it.
