### ISSUE TITLE
Should ktesaErrors function produce stack trace?

### ISSUE THREAD

**Issue by tjsandberg** [krcowles/ktesa#28]
Transferred from Mantis:
Tom wrote: We dump the PHP stack trace on exceptions but not on errors. Wondering if there is a reason for that.

Ken wrote:
Errors operate differently than Exceptions - the getTraceAsString function is for Exceptions. There is a function in php called debug_backtrace() which might work for errors, but would need to be tested. For fatal errors (see list in shutdown handler), execution halts so normal handling isn't available:

> You won't get a stack trace on the fatal error because "FATAL" means script execution stops immediately, i.e. the trace can't be generated through the usual channels. So, if you have set a custom error handler to throw exceptions, it won't be invoked for fatal errors as per the PHP manual

https://stackoverflow.com/questions/8990881/php-log-stack-trace-for-fatal-errors-in-production

This is probably the reason it wasn't attempted before - apparently harder to do in Errors than Exceptions and we were just beginning to learn about error/exception handling.

**Comment by tjsandberg** [comment]
I did a little more research and found several ways we could get the trace from within the error handler. One way is to do this:
$error_string = (new Exception)->getTraceAsString();

Here's a link to the SO article where I found this:
https://stackoverflow.com/questions/19644447/debug-print-backtrace-to-string-for-log-file

**Comment by krcowles** [comment]
Merged a second linked pull request branch with master to resolve this issue, but when the merged w/master was pushed, the issue remained open - the second pull request was removed from the issue. A test site was created for this fix at [https://nmhikes.com/master_7e36ab1](url). When the test site is uploaded to main, this issue and its open pull request will be manually closed.

**Comment by krcowles** [comment]
Manually closing the remaining pull request does not automatically close the linked issue. This issue is closed due to an earlier fix.
