### ISSUE TITLE
Security issues with logging stack trace

### ISSUE THREAD

**Issue by tjsandberg** [krcowles/ktesa#3]
Here's an article that gives an example where the SQL password appeared in the PHP stack trace:
[https://blog.hboeck.de/archives/884-And-then-I-saw-the-Password-in-the-Stack-Trace.html](https://blog.hboeck.de/archives/884-And-then-I-saw-the-Password-in-the-Stack-Trace.html)

The article lists several recommendations for improving security:
1. display_errors is far more dangerous than I was aware of.
2. Unhandled exceptions introduce unexpected risks that I wasn't aware of.
3. In the past I was recommending that people should use PDO with prepared statements if they use MySQL with PHP. I wonder if I should reconsider that, given the circumstances mysqli seems safer (it also supports prepared statements).
4. (From one of the comments) The same happens in java (e.g. with uncaught NullPointerExceptions) and many other languages. Exceptions must be caught.

I think we have most of this covererd, but I wonder about a couple of things:

- Do we catch exceptions in java?
- We should probably find a way to make the error log accessible only to us. Right now, anyone can view ktesa.log by just going to the link. For example: [https://nmhikes.com/htmlErrorPage7_34ba4d7/ktesa.log](https://nmhikes.com/htmlErrorPage7_34ba4d7/ktesa.log)

**Comment by krcowles** [comment]
I always feel like a complete idiot when it comes to security - so I usually have to ask dumb questions to try to get a hold of it. The link you provided, for some reason, doesn’t work when I click it. When I copied and pasted into the address bar, it took me to a strange place that had nothing to do with your topic. There were links in Cyrillic - Russian? Maybe you could try again and resend?

Does the article give more details? E.g. - #1 - like what? #2 - like what? #3 -  “seems”? #4 we’re not using java - it’s completely unrelated to javascript.

Your last point seems like a good idea. Any further thoughts?

**Comment by tjsandberg** [comment]
Looks like the mistake was mine on the url. It is corrected now.

**Comment by tjsandberg** [comment]
Looks like I made the same mistake on the other url. I'll correct that asap. We have a bit of a learning curve about the quirks of Markdown. Notice how your use of the \# sign resulted in cross-links to other issues. For example, #2 turns into a link to this issue! You can use the backslash \\ character to escape. When you're entering text, you can click the Preview tab to see how it looks. See screenshot.

![Screenshot](https://user-images.githubusercontent.com/18223495/95348788-9d6b8100-087b-11eb-95ff-2a3b4a42670e.png)

**Comment by krcowles** [comment]
One recommendation is to set display_errors off in Production mode: 
ini_set('display_errors', 0);
ini_set('display_startup_errors', 0);
While our current server has these as default, we should be explicit in case we move to a different host

**Comment by tjsandberg** [comment]
If we think the default values for these settings really can vary from one server to another, maybe we should use ,htaccess to set them. Otherwise, every script runs with the wrong values until global_boot gets around to setting the values we want.

**Comment by krcowles** [comment]
With your implementation of placing error logs outside of DOCUMENT_ROOT in a private directory, does this resolve this issue? That is, is this issue now ready to be closed?

**Comment by krcowles** [comment]
Stack trace logging has been moved to a private directory outside the project.
