### ISSUE TITLE
Undefined variable error on creating new hike page

### ISSUE THREAD

**Issue by tjsandberg** [krcowles/ktesa#45]
This is on branch clusterPages at commit 14a3a1aa
I get a whoops error when I do the following:
1. Contribute --> Create New Hike
2. Enter hike name and click Submit This Page
3. Click Preview. 

The whoops error is:
Undefined variable: hikeFiles
at …/pages/hikePageTemplate.php199

**Comment by krcowles** [comment]
Good catch - this would have happened for any page with no gpx file. The fix is done (not pushed) but will take me awhile to run through some test cases.

**Comment by krcowles** [comment]
I have pushed the fix, but have not done massive testing on related features of the editor. I am adding an issue to develop a test plan/test cases as we really have none other than back and forth testing between us.

**Comment by krcowles** [comment]
This issue was resolved in the cleanup of issues relating to the introduction of cluster pages.
